//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trending.CoreDigitalInputRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalInput", Namespace="http://schemas.datacontract.org/2004/07/SCADACore.Models")]
    [System.SerializableAttribute()]
    public partial class DigitalInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IOAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OnScanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScanTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IOAddress {
            get {
                return this.IOAddressField;
            }
            set {
                if ((this.IOAddressField.Equals(value) != true)) {
                    this.IOAddressField = value;
                    this.RaisePropertyChanged("IOAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OnScan {
            get {
                return this.OnScanField;
            }
            set {
                if ((this.OnScanField.Equals(value) != true)) {
                    this.OnScanField = value;
                    this.RaisePropertyChanged("OnScan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ScanTime {
            get {
                return this.ScanTimeField;
            }
            set {
                if ((this.ScanTimeField.Equals(value) != true)) {
                    this.ScanTimeField = value;
                    this.RaisePropertyChanged("ScanTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreDigitalInputRef.IDigitalInputService")]
    public interface IDigitalInputService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/GetAll", ReplyAction="http://tempuri.org/IDigitalInputService/GetAllResponse")]
        Trending.CoreDigitalInputRef.DigitalInput[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/GetAll", ReplyAction="http://tempuri.org/IDigitalInputService/GetAllResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/GetForIOAddress", ReplyAction="http://tempuri.org/IDigitalInputService/GetForIOAddressResponse")]
        Trending.CoreDigitalInputRef.DigitalInput GetForIOAddress(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/GetForIOAddress", ReplyAction="http://tempuri.org/IDigitalInputService/GetForIOAddressResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput> GetForIOAddressAsync(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/Create", ReplyAction="http://tempuri.org/IDigitalInputService/CreateResponse")]
        Trending.CoreDigitalInputRef.DigitalInput Create(Trending.CoreDigitalInputRef.DigitalInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/Create", ReplyAction="http://tempuri.org/IDigitalInputService/CreateResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput> CreateAsync(Trending.CoreDigitalInputRef.DigitalInput input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/GetByTagName", ReplyAction="http://tempuri.org/IDigitalInputService/GetByTagNameResponse")]
        Trending.CoreDigitalInputRef.DigitalInput GetByTagName(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalInputService/GetByTagName", ReplyAction="http://tempuri.org/IDigitalInputService/GetByTagNameResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput> GetByTagNameAsync(string tagName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDigitalInputServiceChannel : Trending.CoreDigitalInputRef.IDigitalInputService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DigitalInputServiceClient : System.ServiceModel.ClientBase<Trending.CoreDigitalInputRef.IDigitalInputService>, Trending.CoreDigitalInputRef.IDigitalInputService {
        
        public DigitalInputServiceClient() {
        }
        
        public DigitalInputServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DigitalInputServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalInputServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalInputServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trending.CoreDigitalInputRef.DigitalInput[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Trending.CoreDigitalInputRef.DigitalInput GetForIOAddress(int ioAddress) {
            return base.Channel.GetForIOAddress(ioAddress);
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput> GetForIOAddressAsync(int ioAddress) {
            return base.Channel.GetForIOAddressAsync(ioAddress);
        }
        
        public Trending.CoreDigitalInputRef.DigitalInput Create(Trending.CoreDigitalInputRef.DigitalInput input) {
            return base.Channel.Create(input);
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput> CreateAsync(Trending.CoreDigitalInputRef.DigitalInput input) {
            return base.Channel.CreateAsync(input);
        }
        
        public Trending.CoreDigitalInputRef.DigitalInput GetByTagName(string tagName) {
            return base.Channel.GetByTagName(tagName);
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalInputRef.DigitalInput> GetByTagNameAsync(string tagName) {
            return base.Channel.GetByTagNameAsync(tagName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreDigitalInputRef.IScanService", CallbackContract=typeof(Trending.CoreDigitalInputRef.IScanServiceCallback))]
    public interface IScanService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/StartScan")]
        void StartScan(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/StartScan")]
        System.Threading.Tasks.Task StartScanAsync(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/EndScan")]
        void EndScan(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/EndScan")]
        System.Threading.Tasks.Task EndScanAsync(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/EndAllScans")]
        void EndAllScans();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/EndAllScans")]
        System.Threading.Tasks.Task EndAllScansAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScanServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/AnalogScanDone")]
        void AnalogScanDone(int ioAddress, double value);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IScanService/DigitalScanDone")]
        void DigitalScanDone(int ioAddress, bool value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScanServiceChannel : Trending.CoreDigitalInputRef.IScanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScanServiceClient : System.ServiceModel.DuplexClientBase<Trending.CoreDigitalInputRef.IScanService>, Trending.CoreDigitalInputRef.IScanService {
        
        public ScanServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ScanServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ScanServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ScanServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ScanServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void StartScan(int ioAddress) {
            base.Channel.StartScan(ioAddress);
        }
        
        public System.Threading.Tasks.Task StartScanAsync(int ioAddress) {
            return base.Channel.StartScanAsync(ioAddress);
        }
        
        public void EndScan(int ioAddress) {
            base.Channel.EndScan(ioAddress);
        }
        
        public System.Threading.Tasks.Task EndScanAsync(int ioAddress) {
            return base.Channel.EndScanAsync(ioAddress);
        }
        
        public void EndAllScans() {
            base.Channel.EndAllScans();
        }
        
        public System.Threading.Tasks.Task EndAllScansAsync() {
            return base.Channel.EndAllScansAsync();
        }
    }
}
