//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trending.CoreTagReportRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TagReport", Namespace="http://schemas.datacontract.org/2004/07/SCADACore.Models")]
    [System.SerializableAttribute()]
    public partial class TagReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trending.CoreTagReportRef.IOType TagTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trending.CoreTagReportRef.IOType TagType {
            get {
                return this.TagTypeField;
            }
            set {
                if ((this.TagTypeField.Equals(value) != true)) {
                    this.TagTypeField = value;
                    this.RaisePropertyChanged("TagType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IOType", Namespace="http://schemas.datacontract.org/2004/07/SCADACore.Execptions")]
    public enum IOType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnalogInput = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AnalogOutput = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DigitalInput = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DigitalOutput = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreTagReportRef.ITagReportService")]
    public interface ITagReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagReportService/GetMostRecent", ReplyAction="http://tempuri.org/ITagReportService/GetMostRecentResponse")]
        Trending.CoreTagReportRef.TagReport[] GetMostRecent();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITagReportService/GetMostRecent", ReplyAction="http://tempuri.org/ITagReportService/GetMostRecentResponse")]
        System.Threading.Tasks.Task<Trending.CoreTagReportRef.TagReport[]> GetMostRecentAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITagReportServiceChannel : Trending.CoreTagReportRef.ITagReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TagReportServiceClient : System.ServiceModel.ClientBase<Trending.CoreTagReportRef.ITagReportService>, Trending.CoreTagReportRef.ITagReportService {
        
        public TagReportServiceClient() {
        }
        
        public TagReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TagReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TagReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trending.CoreTagReportRef.TagReport[] GetMostRecent() {
            return base.Channel.GetMostRecent();
        }
        
        public System.Threading.Tasks.Task<Trending.CoreTagReportRef.TagReport[]> GetMostRecentAsync() {
            return base.Channel.GetMostRecentAsync();
        }
    }
}
