//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trending.CoreDigitalOutputRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DigitalOutput", Namespace="http://schemas.datacontract.org/2004/07/SCADACore.Models")]
    [System.SerializableAttribute()]
    public partial class DigitalOutput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IOAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IOAddress {
            get {
                return this.IOAddressField;
            }
            set {
                if ((this.IOAddressField.Equals(value) != true)) {
                    this.IOAddressField = value;
                    this.RaisePropertyChanged("IOAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName {
            get {
                return this.TagNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TagNameField, value) != true)) {
                    this.TagNameField = value;
                    this.RaisePropertyChanged("TagName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CoreDigitalOutputRef.IDigitalOutputService")]
    public interface IDigitalOutputService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/GetAll", ReplyAction="http://tempuri.org/IDigitalOutputService/GetAllResponse")]
        Trending.CoreDigitalOutputRef.DigitalOutput[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/GetAll", ReplyAction="http://tempuri.org/IDigitalOutputService/GetAllResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/GetForIOAddress", ReplyAction="http://tempuri.org/IDigitalOutputService/GetForIOAddressResponse")]
        Trending.CoreDigitalOutputRef.DigitalOutput GetForIOAddress(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/GetForIOAddress", ReplyAction="http://tempuri.org/IDigitalOutputService/GetForIOAddressResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput> GetForIOAddressAsync(int ioAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/Save", ReplyAction="http://tempuri.org/IDigitalOutputService/SaveResponse")]
        void Save(Trending.CoreDigitalOutputRef.DigitalOutput digitalOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/Save", ReplyAction="http://tempuri.org/IDigitalOutputService/SaveResponse")]
        System.Threading.Tasks.Task SaveAsync(Trending.CoreDigitalOutputRef.DigitalOutput digitalOutput);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/SetNewValue", ReplyAction="http://tempuri.org/IDigitalOutputService/SetNewValueResponse")]
        void SetNewValue(int ioAddress, bool newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/SetNewValue", ReplyAction="http://tempuri.org/IDigitalOutputService/SetNewValueResponse")]
        System.Threading.Tasks.Task SetNewValueAsync(int ioAddress, bool newValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/Create", ReplyAction="http://tempuri.org/IDigitalOutputService/CreateResponse")]
        Trending.CoreDigitalOutputRef.DigitalOutput Create(Trending.CoreDigitalOutputRef.DigitalOutput output);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/Create", ReplyAction="http://tempuri.org/IDigitalOutputService/CreateResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput> CreateAsync(Trending.CoreDigitalOutputRef.DigitalOutput output);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/GetByTagName", ReplyAction="http://tempuri.org/IDigitalOutputService/GetByTagNameResponse")]
        Trending.CoreDigitalOutputRef.DigitalOutput GetByTagName(string tagName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDigitalOutputService/GetByTagName", ReplyAction="http://tempuri.org/IDigitalOutputService/GetByTagNameResponse")]
        System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput> GetByTagNameAsync(string tagName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDigitalOutputServiceChannel : Trending.CoreDigitalOutputRef.IDigitalOutputService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DigitalOutputServiceClient : System.ServiceModel.ClientBase<Trending.CoreDigitalOutputRef.IDigitalOutputService>, Trending.CoreDigitalOutputRef.IDigitalOutputService {
        
        public DigitalOutputServiceClient() {
        }
        
        public DigitalOutputServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DigitalOutputServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalOutputServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DigitalOutputServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trending.CoreDigitalOutputRef.DigitalOutput[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public Trending.CoreDigitalOutputRef.DigitalOutput GetForIOAddress(int ioAddress) {
            return base.Channel.GetForIOAddress(ioAddress);
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput> GetForIOAddressAsync(int ioAddress) {
            return base.Channel.GetForIOAddressAsync(ioAddress);
        }
        
        public void Save(Trending.CoreDigitalOutputRef.DigitalOutput digitalOutput) {
            base.Channel.Save(digitalOutput);
        }
        
        public System.Threading.Tasks.Task SaveAsync(Trending.CoreDigitalOutputRef.DigitalOutput digitalOutput) {
            return base.Channel.SaveAsync(digitalOutput);
        }
        
        public void SetNewValue(int ioAddress, bool newValue) {
            base.Channel.SetNewValue(ioAddress, newValue);
        }
        
        public System.Threading.Tasks.Task SetNewValueAsync(int ioAddress, bool newValue) {
            return base.Channel.SetNewValueAsync(ioAddress, newValue);
        }
        
        public Trending.CoreDigitalOutputRef.DigitalOutput Create(Trending.CoreDigitalOutputRef.DigitalOutput output) {
            return base.Channel.Create(output);
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput> CreateAsync(Trending.CoreDigitalOutputRef.DigitalOutput output) {
            return base.Channel.CreateAsync(output);
        }
        
        public Trending.CoreDigitalOutputRef.DigitalOutput GetByTagName(string tagName) {
            return base.Channel.GetByTagName(tagName);
        }
        
        public System.Threading.Tasks.Task<Trending.CoreDigitalOutputRef.DigitalOutput> GetByTagNameAsync(string tagName) {
            return base.Channel.GetByTagNameAsync(tagName);
        }
    }
}
